### ISSUE TITLE
Install failure on Xubuntu

### ISSUE THREAD

**Issue by thomastiotto** [mariomulansky/PySpike#69]
Using Xubuntu 20.04.6, python 3.0.0, setuptools 68.0.0 I can't install pyspike from source (I also tried `pip install pyspike`):

```python setup.py build_ext --inplace
running build_ext
Traceback (most recent call last):
  File "/home/p291020/PySpike/setup.py", line 84, in <module>
    setup(
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
    new_ext = cythonize(
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 990, in cythonize
    module_list, module_metadata = create_extension_list(
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 839, in create_extension_list
    kwds = deps.distutils_info(file, aliases, base).values
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 691, in distutils_info
    return (self.transitive_merge(filename, self.distutils_info0, DistutilsInfo.merge)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 700, in transitive_merge
    return self.transitive_merge_helper(
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 712, in transitive_merge_helper
    for next in outgoing(node):
  File "Cython/Utils.py", line 129, in Cython.Utils.cached_method.wrapper
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 613, in cimported_files
    pxd_file = self.find_pxd(module, filename)
  File "Cython/Utils.py", line 129, in Cython.Utils.cached_method.wrapper
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 594, in find_pxd
    pxd = self.context.find_pxd_file(relative, source_file_path=filename)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 281, in find_pxd_file
    pxd = self.search_include_directories(
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 309, in search_include_directories
    return search_include_directories(
  File "Cython/Utils.py", line 90, in Cython.Utils.cached_function.wrapper
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/site-packages/Cython/Compiler/Main.py", line 702, in search_include_directories
    path = os.path.join(dirname, dotted_filename)
  File "/home/p291020/miniconda3/envs/brian/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not numpy_include```

**Comment by dionperd** [comment]
I confirm the error trying to install pyspike in Ubuntu on top of NEST docker image.

**Comment by thomaskreuz** [comment]
Sorry for the late reply.

We addressed [#70](https://github.com/mariomulansky/PySpike/issues/70) with PR [#75](https://github.com/mariomulansky/PySpike/pull/75).

Could you please let us know if this is now resolved as well or if you still get the same error message.

Thanks a lot!
